=== GlassFish

==== Using `asadmin`

The following `asadmin` commands are provided for Glassfish:

- get-chainlink
- get-chainlink-job-operator -j <job operator name>
- get-chainlink-deployment -d <deployment name>
- get-chainlink-deployment-job-operator -d <deployment name> -j <job operator name>
- set-chainlink [ -f <filename> | -b <base 64 of file> ]
- set-chainlink-job-operator [ -f <filename> | -b <base 64 of file> ]
- set-chainlink-deployment [ -f <filename> | -b <base 64 of file> ]
- set-chainlink-deployment-job-operator -d <deployment name> [ -f <filename> | -b <base 64 of file> ]
- delete-chainlink
- delete-chainlink-job-operator -j <job operator name>
- delete-chainlink-deployment -d <deployment name>
- delete-chainlink-deployment-job-operator -d <deployment name> -j <job operator name>
- reload-chainlink

[NOTE]
====
The output of the `get-chainlink-*` commands are not formatted. To make it easier to read you might
consider using them with the `asadmin` terse option (`-t` or `--terse`) and combining them with an xml
formatter. e.g.

`./asadmin -t get-chainlink | xmllint --format -`
====

The options for the commands all function mor or less the same across commands. Here is a quick
reference, though they are elaborated on per command. In this section the term base64 refers to
the URL safe variant of the encoding described in http://tools.ietf.org/html/rfc4648#page-7[RFC 4648]

[cols="1,3"]
|===
|Flag |Parameter
|`-j \| --job-operator`
|The name attribute of the `job-operator` element the command is to be applied to. There is not default value.
|`-d \| --deployment`
|The name attribute of the `deployment` element that either the command is to be applied to or that
contains the `job-operator` element the command is to be applied to. There is not default value.
|`-f \| --file`
|The filename of a file containing the xml snippet to be applied to the model. There is not default value.
|`-b \| --base64`
|A base64 encoded string of the xml snippet to be applied to the model. There is not default value.
|`--target`
|The target for the command. Defaults to 'server'.
|===


[TIP]
====
The recommended way of updating Chainlink's configuration is to retrieve the existing configuration,
modify it, and then upload the modifications. e.g. To change the whole server config:

[source,shell]
----
./asadmin -t get-chainlink | xmllint --format - > ~/config.xml
vim ~/config.xml # Make changes here
./asadmin set-chainlink -f ~/config.xml
----

Or just a single operator:

[source,shell]
----
./asadmin -t get-chainlink-deployment-job-operator -d default -j default | xmllint --format - > ~/config.xml
vim ~/config.xml # Make changes here
./asadmin set-chainlink-deployment-job-operator -d default -j default -f ~/config.xml
----
====

===== get-chainlink

Return the entire Chainlink subsystem configuration. This command should never fail. The output is
xml from the schema `chainlink-subsystem_1_0.xsd`.

===== get-chainlink-job-operator -j <job operator name>

Return the configuration from a single named `job-operator` element. The output is an xml snippet xml
of a `job-operator` element from the schema `chainlink_1_0.xsd`. This command will fail if:

1. The `job-operator` parameter is not provided.
2. The named `job-operator` element does not exist.

[cols="1,3"]
|===
|Flag |Parameter
|`-j \| --job-operator`
|The name attribute of the `job-operator` element to be retrieved. The element must
be a child of the `subsystem` element in the schema.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== get-chainlink-deployment -d <deployment name>

Return the configuration from a single named `deployment` element. The output is an xml snippet xml of
a `deployment` element from the schema `chainlink_1_0.xsd`.

This command will fail if:

1. The `deployment` parameter is not provided.
2. The named `deployment` element does not exist.

[cols="1,3"]
|===
|Flag |Parameter
|`-d \| --deployment`
|The name attribute of the `deployment` element to be retrieved.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== get-chainlink-deployment-job-operator -d <deployment name> -j <job operator name>

Return the configuration from a single named `job-operator` element from a named `deployment` element. The
output is an xml snippet xml of a `job-operator` element from the schema `chainlink_1_0.xsd`.

This command will fail if:

1. Either the `deployment` or `job-operator` parameter is not provided.
2. The named `deployment` element does not exist.
3. The named `job-operator` element does not exist.

[cols="1,3"]
|===
|Flag |Parameter
|`-d \| --deployment`
|The name attribute of the `deployment` element that contains the `job-operator`
element.
|`-j \| --job-operator`
|The name attribute of the `job-operator` element to be retrieved. The element must
be a child of the `deployment` element in the schema.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== set-chainlink [ -f <filename> | -b <base 64 of file> ]

Set Chainlink's configuration to match that of the provided xml. This command is an 'upsert'. The
command will fail if:

1. Neither of the arguments `file` or `base64` are provided.
2. Both of the arguments `file` or `base64` are provided.
3. The xml content provided is not valid according to the schema `chainlink-subsystem_1_0.xsd`.

[cols="1,3"]
|===
|Flag |Parameter
|`-f \| --file`
|The filename of a file containing the xml model.
|`-b \| --base64`
|A base64 encoded string of the xml model.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== set-chainlink-job-operator [ -f <filename> | -b <base 64 of file> ]

Set a named `job-operator` element to match that of the provided xml.  This command is an 'upsert'.
The command will fail if:

1. Neither of the arguments `file` or `base64` are provided.
2. Both of the arguments `file` or `base64` are provided.
3. The xml content provided is not a valid snipped of the `job-operator` element in the schema
   `chainlink_1_0.xsd`.

[cols="1,3"]
|===
|Flag |Parameter
|`-f \| --file`
|The filename of a file containing the xml model.
|`-b \| --base64`
|A base64 encoded string of the xml model.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== set-chainlink-deployment [ -f <filename> | -b <base 64 of file> ]

Set a named `deployment` element to match that of the provided xml.  This command is an 'upsert'.
The command will fail if:

1. Neither of the arguments `file` or `base64` are provided.
2. Both of the arguments `file` or `base64` are provided.
3. The xml content provided is not a valid snipped of the `deployment` element in the schema
   `chainlink_1_0.xsd`.

[cols="1,3"]
|===
|Flag |Parameter
|`-f \| --file`
|The filename of a file containing the xml model.
|`-b \| --base64`
|A base64 encoded string of the xml model.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== set-chainlink-deployment-job-operator -d <deployment name> [ -f <filename> | -b <base 64 of file> ]

Set a named `job-operator` element from a named `deployment` element to match that of the provided
xml. This command is an 'upsert'. The command will fail if:

1. The `deployment` argument is not provided.
2. The named `deployment` element does not exist.
3. Neither of the arguments `file` or `base64` are provided.
4. Both of the arguments `file` or `base64` are provided.
5. The xml content provided is not a valid snipped of the `job-operator` element in the schema
   `chainlink_1_0.xsd`.

[cols="1,3"]
|===
|Flag |Parameter
|`-d \| --deployment`
|The name attribute of the `deployment` element that contains/will contain the
                   `job-operator` element.
|`-f \| --file`
|The filename of a file containing the xml model.
|`-b \| --base64`
|A base64 encoded string of the xml model.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== delete-chainlink

Remove all Chainlink configuration. This command will always succeed. This command will return the
existing configuration as per the `get-chainlink` command.

===== delete-chainlink-job-operator -j <job operator name>

Remove a single named `job-operator` element.  This command will return the existing configuration
as per the `get-chainlink-job-operator` command. This command will fail if:

1. The `job-operator` parameter is not provided.
2. The named `job-operator` element does not exist.

[cols="1,3"]
|===
|Flag |Parameter
|`-j \| --job-operator`
|The name attribute of the `job-operator` element to be removed. The element must
                   be a child of the `subsystem` element in the schema.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== delete-chainlink-deployment -d <deployment name>

Remove a single named `deployment` element. This command will return the existing configuration as
per the `get-chainlink-deployment` command. The command will fail if:

1. The `deployment` argument is not provided.
2. The named `deployment` element does not exist.

[cols="1,3"]
|===
|Flag |Parameter
|`-d \| --deployment`
|The name attribute of the `deployment` element to be removed.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== delete-chainlink-deployment-job-operator -d <deployment name> -j <job operator name>

Remove a single `job-operator` element contained in a named `deployment` element.  This command will
return the existing configuration as per the `get-chainlink-deployment-job-operator` command. This
command will fail if:

1. Either the `deployment` or `job-operator` parameter is not provided.
2. The named `deployment` element does not exist.
3. The named `job-operator` element does not exist.

[cols="1,3"]
|===
|Flag |Parameter
|`-d \| --deployment`
|The name attribute of the `deployment` element that contains the `job-operator`
                   element.
|`-j \| --job-operator`
|The name attribute of the `job-operator` element to be removed. The element must
                   be a child of the `deployment` element in the schema.
|`--target`
|The target for the command. Defaults to 'server'.
|===

===== reload-chainlink

Apply the configuration changes to the Chainlink runtime.

[TIP]
====
Accidentally call `delete-chainlink`? The existing configuration is returned so you can save it to a
file and then upload it again with `set-chainlink`. Remember, configuration changes are not visible to
Chainlink until `reload-chainlink` is called.
====

==== Using the REST api

These commands are also provided through Glassfish's REST api. The commands are accessed through with
the following rules.

1. Commands prefixed with `get-` are accessed by sending a GET request.
2. Commands prefixed with `set-` are accessed by sending a POST request.
3. Commands prefixed with `delete-` are accessed by sending a DELETE request.

Here is an example using curl to create, inspect and then remove a job operator.

[source,shell]
----
# The file argument will load the file from the servers FS.
# Instead this encodes a local file so it can be included in the request.
ENCODED_FILE="$(base64 -w0 ~/job.xml | tr '+/' '-_')"

# Have a look at what's there
curl -X GET \
        -H "Accept: application/xml" \
        http://localhost:4848/management/domain/get-chainlink \
    | xmllint --format -

# Create the job operator
curl -X POST \
        -H "Accept: application/xml" \
        -H "X-Requested-By: GlassFish REST HTML interface" \
        -d "base64=${ENCODED_FILE}" \
        http://localhost:4848/management/domain/set-chainlink-job-operator \
    | xmllint --format -

# Have a look at the job operator we just uploaded
curl -X GET \
        -H "Accept: application/xml" \
        http://localhost:4848/management/domain/get-chainlink-job-operator \
    | xmllint --format -

# Remove the job operator
curl -X DELETE \
        -H "Accept: application/xml" \
        -H "X-Requested-By: GlassFish REST HTML interface" \
        -d "job-operator=default" \
        http://localhost:4848/management/domain/delete-chainlink-job-operator \
    | xmllint --format -
----