language: java

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  # Integration tests
  - BUILD_ARGS="-T"
  # TCK SE
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-memory     -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-cdi    -r re-memory     -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-spring -r re-memory     -c se"
  - BUILD_ARGS="-I -t tr-infinispan -i in-batch  -r re-memory     -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-infinispan -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-gridgain   -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-hazelcast  -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-ehcache    -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-jdbc       -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-jpa        -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-jdbc       -c se -d db-postgresql"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-jpa        -c se -d db-postgresql"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-redis      -c se"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-mongo      -c se"
  # TCK EE
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-memory     -c glassfish"
  # - BUILD_ARGS="-I -t tr-local      -i in-cdi    -r re-memory     -c glassfish" # Need to majic OSGI deps in inject-cdi module somehow
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-memory     -c tomee"
  - BUILD_ARGS="-I -t tr-local      -i in-cdi    -r re-memory     -c tomee"
  - BUILD_ARGS="-I -t tr-local      -i in-batch  -r re-memory     -c wildfly"
  - BUILD_ARGS="-I -t tr-local      -i in-cdi    -r re-memory     -c wildfly"

services:
  - mongodb
  - redis-server

addons:
  postgresql: "9.2"

before_script: if [ "${BUILD_ARGS}" == *"db-postgresql"* ]; then psql -c 'create database chainlink;' -U postgres; fi

script: ./testsuite ${BUILD_ARGS}

after_failure: if [ -e tck/glassfish/target/glassfish4/glassfish/domains/domain1/logs/server.log ]; then cat tck/glassfish/target/glassfish4/glassfish/domains/domain1/logs/server.log; fi

