language: java

sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Xms512m -Xmx512m"
    - JAVA_OPTS="-Xms512m -Xmx512m"
    - JBOSS_OPTS="-Xms1024m -Xmx1024m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+CMSClassUnloadingEnabled"
  matrix:
    # Integration tests
    - BUILD_ARGS="-T -l -d h2"
    - BUILD_ARGS="-T -l -d postgresql"
    # TCK SE
    - BUILD_ARGS="-I -t local      -i batch  -r memory     -c se"
    - BUILD_ARGS="-I -t local      -i cdi    -r memory     -c se"
    - BUILD_ARGS="-I -t local      -i spring -r memory     -c se"
    # No Coherence deps on build server
    #- BUILD_ARGS="-I -t coherence  -i batch  -r memory     -c se"
    # Broken
    #- BUILD_ARGS="-I -t infinispan -i batch  -r memory     -c se"
    # Broken
    #- BUILD_ARGS="-I -t jgroups    -i batch  -r memory     -c se"
    # There is an issue propagating the correct StepContext BatchStatus to the JobContext
    #- BUILD_ARGS="-I -t gridgain   -i batch  -r memory     -c se"
    #- BUILD_ARGS="-I -t hazelcast  -i batch  -r memory     -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r infinispan -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r gridgain   -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r hazelcast  -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r ehcache    -c se"
    # No Coherence deps on build server
    #- BUILD_ARGS="-I -t local      -i batch  -r coherence  -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r jdbc       -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r jpa        -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r jdbc       -c se -d postgresql"
    - BUILD_ARGS="-I -t local      -i batch  -r jpa        -c se -d postgresql"
    # For some reason the mariadb driver is extremely slow. Needs investigating.
    #- BUILD_ARGS="-I -t local      -i batch  -r jdbc       -c se -d mariadb"
    #- BUILD_ARGS="-I -t local      -i batch  -r jpa        -c se -d mariadb"
    - BUILD_ARGS="-I -t local      -i batch  -r redis      -c se"
    - BUILD_ARGS="-I -t local      -i batch  -r mongo      -c se"
    # TCK EE
    # These are failing two of the TransactionTests since using managed thread factory. Need to investigate.
    # - BUILD_ARGS="-I -t local      -i batch  -r memory     -c glassfish"
    # - BUILD_ARGS="-I -t local      -i cdi    -r memory     -c glassfish"
    - BUILD_ARGS="-I -t local      -i batch  -r memory     -c tomee"
    - BUILD_ARGS="-I -t local      -i cdi    -r memory     -c tomee"
    - BUILD_ARGS="-I -t local      -i batch  -r memory     -c wildfly"
    - BUILD_ARGS="-I -t local      -i cdi    -r memory     -c wildfly"
    - BUILD_ARGS="-I -t local      -i batch  -r infinispan -c wildfly"

services:
  - mongodb
  - redis-server

addons:
  postgresql: "9.2"

before_script:
  - mysql -e 'create database chainlink;' -u root
  - cat "${TRAVIS_BUILD_DIR}/ext/schema-mariadb.sql" | mysql -u root chainlink
  - psql -c 'create database chainlink;' -U postgres
  - cat "${TRAVIS_BUILD_DIR}/ext/schema-postgresql.sql" | psql -U postgres -d chainlink

script: ./testsuite ${BUILD_ARGS}

after_failure:
  - if [ -e tck/glassfish/target/glassfish4/glassfish/domains/domain1/logs/server.log ]; then cat tck/glassfish/target/glassfish4/glassfish/domains/domain1/logs/server.log; fi
  - if [ -e tck/se/target/chainlinkd/*/log/console*.log ]; then cat tck/se/target/chainlinkd/*/log/console*.log; fi

