language: java

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  # Integration tests
  - BUILD_ARGS="-T"
  # TCK every regular repositories per container
  - BUILD_ARGS="-I -c se"
  - BUILD_ARGS="-I -t tr-local -i in-batch -c glassfish"
    IS_GLASSFISH="true"
  - BUILD_ARGS="-I -t tr-local -i in-batch -c tomee"
  - BUILD_ARGS="-I -t tr-local -i in-batch -c wildfly"
  # TCK every container per installed repo
  - BUILD_ARGS="-I -t tr-local -i in-batch -r re-jpa,re-jdbc -d db-postgresql"
    IS_POSTGRES="true"
  - BUILD_ARGS"-I -t tr-local -i in-batch -r re-redis"
  - BUILD_ARGS"-I -t tr-local -i in-batch -r re-mongo"

services:
  - mongodb
  - redis-server

addons:
  postgresql: "9.2"

before_script: test "${IS_POSTGRES}" == "true" && psql -c 'create database chainlink;' -U postgres

script: ./testsuite ${BUILD_ARGS}

after_failure: test "${IS_GLASSFISH}" == "true" && cat tck/glassfish/target/glassfish4/glassfish/domains/domain1/logs/server.log

