#!/bin/bash
#
# @author <a href="mailto:brent.n.douglas@gmail.com">Brent Douglas</a>
#

RETVAL=0
UNINSTALL=0

usage() {
  echo "Usage: install [-h] [-u]"
  echo "  -u Uninstall"
  echo "  -h Print usage"
}

install() {
  [ -d app ] || {
    mkdir app
  }
}

uninstall() {
  echo "Successfully uninstalled Chainlink."
}

while getopts "hu" opt; do
  case ${opt} in
    h)
      usage
      ;;

    u)
      UNINSTALL=1
      ;;

    \?)
      echo "Invalid option: -${OPTARG}"
      usage
      exit 1
      ;;

    :)
      echo "Option -${OPTARG} requires an argument."
      usage
      exit 1
      ;;
  esac
done

if [ ${UNINSTALL} -eq 0 ]; then
  install
else
  uninstall
fi

exit ${RETVAL}
